# Generated by Django 3.1.7 on 2021-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_auto_20210724_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
